- src/main/java/Growup/spring/email/service/EmailService.java
- src/main/java/Growup/spring/member/Controller/UserController.java
- src/main/java/Growup/spring/member/service/UserService.java
- src/main/java/Growup/spring/member/service/UserServiceImpl.java
- src/main/java/Growup/spring/security/JwtProvider.java
> 메일인증 응답 내용 수정

- src/main/java/Growup/spring/constant/exeption/ExceptionAdvice.java
- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/email/converter/EmailConverter.java
- src/main/java/Growup/spring/email/dto/EmailDtoReq.java
- src/main/java/Growup/spring/email/dto/EmailDtoRes.java
- src/main/java/Growup/spring/email/service/EmailService.java
- src/main/java/Growup/spring/member/Controller/UserController.java
- src/main/java/Growup/spring/member/dto/UserDtoReq.java
- src/main/java/Growup/spring/member/dto/UserDtoRes.java
- src/main/java/Growup/spring/member/repository/UserRepository.java
- src/main/java/Growup/spring/member/service/UserService.java
- src/main/java/Growup/spring/member/service/UserServiceImpl.java
- src/main/java/Growup/spring/security/ExceptionHandlerFilter.java
- src/main/java/Growup/spring/security/JwtAuthenticationFilter.java
- src/main/java/Growup/spring/security/JwtProvider.java
- src/main/java/Growup/spring/security/SecurityConfig.java
- src/main/java/Growup/spring/security/handler/CustomAuthenticationEntryPoint.java
> 로그아웃, 비밀번호 재설정, 이메일인증 폼 변경

- build.gradle
- src/main/java/Growup/spring/media/config/KurentoConfig.java
- src/main/java/Growup/spring/media/handler/CallHandler.java
- src/main/java/Growup/spring/media/rooms/Room.java
- src/main/java/Growup/spring/media/rooms/RoomManager.java
- src/main/java/Growup/spring/media/users/UserSession.java
> [FEAT] 화면 공유 기능 구현

- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/domain/Liked.java
- src/main/java/Growup/spring/domain/Participate.java
- src/main/java/Growup/spring/growRoom/domain/GrowRoom.java
- src/main/java/Growup/spring/growRoom/domain/Pin.java
- src/main/java/Growup/spring/growRoom/domain/PinComment.java
- src/main/java/Growup/spring/growRoom/dto/AddGrowRoomRequest.java
- src/main/java/Growup/spring/security/CustomUserDetail.java
- src/main/java/Growup/spring/security/JpaUserDetailsService.java
- src/main/java/Growup/spring/security/SecurityConfig.java
- src/main/java/Growup/spring/user/controller/UserController.java
- src/main/java/Growup/spring/user/converter/UserConverter.java
- src/main/java/Growup/spring/user/dto/RefreshTokenRes.java
- src/main/java/Growup/spring/user/dto/UserDtoReq.java
- src/main/java/Growup/spring/user/dto/UserDtoRes.java
- src/main/java/Growup/spring/user/model/Enum/UserRole.java
- src/main/java/Growup/spring/user/model/Enum/UserState.java
- src/main/java/Growup/spring/user/model/Prefer.java
- src/main/java/Growup/spring/user/model/User.java
- src/main/java/Growup/spring/user/model/UserPrefer.java
- src/main/java/Growup/spring/user/repository/UserRepository.java
- src/main/java/Growup/spring/user/service/UserService.java
- src/main/java/Growup/spring/user/service/UserServiceImpl.java
user 관련 오타수정 및 spring security cors 비활성화 제거
> [FIX] 오타수정, cors 비활성화 제거

- .github/workflows/dev_deploy.yml
> 애플리케이션 이름 수정

- src/main/java/Growup/spring/todoList/controller/TodoListController.java
- src/main/java/Growup/spring/todoList/converter/TodoListConverter.java
- src/main/java/Growup/spring/todoList/dto/TodoDtoListReq.java
- src/main/java/Growup/spring/todoList/dto/TodoDtoListRes.java
- src/main/java/Growup/spring/todoList/model/Enum/TodoStatus.java
- src/main/java/Growup/spring/todoList/model/TodoList.java
- src/main/java/Growup/spring/todoList/repository/TodoListRepository.java
- src/main/java/Growup/spring/todoList/service/TodoListImpl.java
- src/main/java/Growup/spring/todoList/service/TodoListService.java
- src/main/java/Growup/spring/user/model/User.java
> [FEAT] ✨ 투두리스트 조회,등록 API 구현/37

- .platform/nginx/nginx.conf
- src/main/java/Growup/spring/constant/handler/TodoListHandler.java
- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/domain/Liked.java
- src/main/java/Growup/spring/domain/Participate.java
- src/main/java/Growup/spring/todoList/controller/TodoListController.java
- src/main/java/Growup/spring/todoList/dto/TodoDtoListReq.java
- src/main/java/Growup/spring/todoList/dto/TodoDtoListRes.java
- src/main/java/Growup/spring/todoList/service/TodoListImpl.java
- src/main/java/Growup/spring/todoList/service/TodoListService.java
- src/main/java/Growup/spring/user/model/User.java
투두리스트 상태변화- 체크표시시 ACTIVE, 체크표시 삭제시 -NONACTIVE로 상태 변화 api 구현
> [FEAT] ✨ 투두리스트 체크표시(상태변화) API 구현 

- .platform/nginx/nginx.conf
Reverts UMC5-GrowUp/GrowUp_BackEnd#67
> Revert "수정"

- src/main/java/Growup/spring/todoList/controller/TodoListController.java
- src/main/java/Growup/spring/todoList/converter/TodoListConverter.java
- src/main/java/Growup/spring/todoList/dto/TodoDtoListReq.java
- src/main/java/Growup/spring/todoList/dto/TodoDtoListRes.java
- src/main/java/Growup/spring/todoList/service/TodoListImpl.java
- src/main/java/Growup/spring/todoList/service/TodoListService.java
> [FEAT]투두리스트 내용 수정 API 구현 

- src/main/java/Growup/spring/email/service/EmailService.java
> [FIX] 인증 url 수정 🎉 

- src/main/java/Growup/spring/participate/controller/ParticipateController.java
- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
- src/main/java/Growup/spring/participate/model/Participate.java
- src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
- src/main/java/Growup/spring/participate/service/ParticipateService.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FEAT] liveRoom Paging기능 추가 

- build.gradle
> fix(build.gradle): kurento 최신 버전으로 수정

- src/main/java/Growup/spring/calender/controller/CalenderController.java
- src/main/java/Growup/spring/calender/converter/CalenderConverter.java
- src/main/java/Growup/spring/calender/dto/CalenderDtoReq.java
- src/main/java/Growup/spring/calender/dto/CalenderRes.java
- src/main/java/Growup/spring/calender/model/Calender.java
- src/main/java/Growup/spring/calender/model/Enum/CalenderColor.java
- src/main/java/Growup/spring/calender/model/Enum/CalenderStatus.java
- src/main/java/Growup/spring/calender/repository/CalenderRepository.java
- src/main/java/Growup/spring/calender/service/CalenderService.java
- src/main/java/Growup/spring/calender/service/CalenderServiceimpl.java
- src/main/java/Growup/spring/user/model/User.java
년/월/일로 해당하는 날짜에 해야할 일(목록) 등록 api 구현 완료
> [FEAT] 캘린더 해당 날짜- 할일 등록 API 작성 🎉

- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
- src/main/java/Growup/spring/growRoom/converter/GrowRoomConverter.java
- src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoReq.java
- src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
- src/main/java/Growup/spring/growRoom/model/GrowRoom.java
- src/main/java/Growup/spring/growRoom/model/Post.java
- src/main/java/Growup/spring/growRoom/repository/GrowRoomCategoryRepository.java
- src/main/java/Growup/spring/growRoom/repository/GrowRoomRepository.java
- src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
- src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
GrowRoom
- 수정 api 구현
- growroom 권한에 따라 수정 가능
- update 함수 수정
- api 주소 수정
- update 권한
- delete 권한
- delete 상태변경으로 수정
> 그로우룸 수정, 삭제 API

- src/main/java/Growup/spring/growRoom/converter/RecruitmentPeriodConverter.java
- src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoReq.java
- src/main/java/Growup/spring/growRoom/dto/GrowRoomDtoRes.java
- src/main/java/Growup/spring/growRoom/model/GrowRoom.java
- src/main/java/Growup/spring/growRoom/model/Post.java
- src/main/java/Growup/spring/growRoom/model/component/RecruitmentPeriod.java
- src/main/java/Growup/spring/growRoom/repository/RecruitmentPeriodRepository.java
- src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
- src/main/resources/application.yml
- 모집기간 추가
RecruitmentPeriod
- 테이블 추가
> GrowRoom 모집기간 추가

- src/main/java/Growup/spring/constant/status/ErrorStatus.java
[FIX] 사용중인 닉네임 HttpStatus.BAD_REQUEST -> HttpStatus.OK 로 개발단계에선 수정
> [FIX] 사용중인 닉네임 HttpStatus.BAD_REQUEST -> HttpStatus.OK 로 개발단계에선 수정

- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/growRoom/controller/PinCommentController.java
- src/main/java/Growup/spring/growRoom/controller/PinController.java
- src/main/java/Growup/spring/growRoom/converter/PinCommentConverter.java
- src/main/java/Growup/spring/growRoom/dto/PinCommentDtoReq.java
- src/main/java/Growup/spring/growRoom/dto/PinCommentDtoRes.java
- src/main/java/Growup/spring/growRoom/dto/PinDtoRes.java
- src/main/java/Growup/spring/growRoom/model/GrowRoom.java
- src/main/java/Growup/spring/growRoom/model/PinComment.java
- src/main/java/Growup/spring/growRoom/repository/PinCommentRepository.java
- src/main/java/Growup/spring/growRoom/service/PinCommentService.java
- src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
- src/main/java/Growup/spring/growRoom/service/PinServiceImpl.java
- 대댓글 생성
- 대댓글 조회
- 대댓글 수정
- 대댓글 삭제
Pin
- 댓글에 댓글 id 출력 (대댓글 접근 위함)
> PinComment

- src/main/java/Growup/spring/calender/controller/CalenderController.java
- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/participate/controller/ParticipateController.java
- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
- src/main/java/Growup/spring/participate/model/Participate.java
- src/main/java/Growup/spring/participate/model/ParticipateTime.java
- src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
- src/main/java/Growup/spring/participate/repository/ParticipateTimeRepository.java
- src/main/java/Growup/spring/participate/service/ParticipateService.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
- src/main/java/Growup/spring/todoList/controller/TodoListController.java
[Feat] 라이브룸 입장,퇴장 api 구현/ [Fix] 캘린더,투두리스트 작성자 작성
> [Feat] 라이브룸 입장,퇴장 api 구현/ [Fix] 캘린더,투두리스트 작성자 작성

- src/main/java/Growup/spring/security/SecurityConfig.java
> [FIX] cors 웹배포 도메인 추가

- src/main/java/Growup/spring/email/service/EmailService.java
[FIX] cors 웹배포 도메인 (이메일 인증) 수정
> [FIX] cors 웹배포 도메인 (이메일 인증) 수정

- src/main/java/Growup/spring/growRoom/controller/GrowRoomController.java
- src/main/java/Growup/spring/growRoom/controller/PinController.java
- src/main/java/Growup/spring/growRoom/dto/PinDtoRes.java
- src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
- src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
- src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
- src/main/java/Growup/spring/security/SecurityConfig.java
- API 주소 수정
- 로그인 안 되었을 때 인기글 조회 API 추가
PinController
- API 주소 수정
> GrowRoomController

- src/main/java/Growup/spring/security/JwtProvider.java
> [FIX]jwt 개발단계 시간 수정

- src/main/resources/application.yml
> [FIX] 파일 업로드 크기 수정

- src/main/java/Growup/spring/growRoom/service/GrowRoomService.java
- src/main/java/Growup/spring/participate/controller/ParticipateController.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
- src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
- src/main/java/Growup/spring/participate/service/ParticipateService.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> ParticipateController

- src/main/java/Growup/spring/GrowupApplication.java
- src/main/java/Growup/spring/constant/status/ErrorStatus.java
- src/main/java/Growup/spring/liked/service/LikedServiceImpl.java
- src/main/java/Growup/spring/participate/controller/ParticipateController.java
- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
- src/main/java/Growup/spring/participate/model/ParticipateTime.java
- src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
- src/main/java/Growup/spring/participate/service/ParticipateService.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
- src/main/java/Growup/spring/user/service/UserServiceImpl.java
[FIX] 그로우룸 참여자(시간) 관련 api 구현완료
> [FIX] 그로우룸 참여자(시간) 관련 api 구현완료

- src/main/java/Growup/spring/GrowupApplication.java
- src/main/java/Growup/spring/growRoom/controller/PinCommentController.java
- src/main/java/Growup/spring/growRoom/controller/PinController.java
- src/main/java/Growup/spring/growRoom/service/CleanupTask.java
- src/main/java/Growup/spring/growRoom/service/GrowRoomCategoryServiceImpl.java
- src/main/java/Growup/spring/growRoom/service/PinCommentService.java
- src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
- src/main/java/Growup/spring/growRoom/service/PinService.java
- src/main/java/Growup/spring/growRoom/service/PinServiceImpl.java
jwtProvider를 Controller에서만 실행
스케쥴링을 사용하도록 변경
모집기간, 모집인원이 다 찬 경우 모집마감으로 그로우룸의 상태변경
> 수정 및 기능 추가

- src/main/java/Growup/spring/growRoom/service/CleanupTask.java
- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FEAT]참여자 관련 코드 수정

- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FIX] 그로우룸 참여시 에러 수정

- src/main/java/Growup/spring/growRoom/service/PinCommentServiceImpl.java
> PinComment 생성 오류

- src/main/java/Growup/spring/security/SecurityConfig.java
> cors url 수정

- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
> participateId 응답으로 수정

- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
> [FIX]participateId 응답으로 수정

- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
[FIX}랭킹별 누적시간(주간/월간/일간) 조회시 수정
> [FIX}랭킹별 누적시간(주간/월간/일간) 조회시 수정

- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
라이브룸 입장시 - 방장이 입장시- 참여시간 participatetime 테이블에 누적되는 것 삭제 
라이브룸 퇴장시 - 퇴장시 나가는 시간이 endtime이 null인 곳에만 나가는 시간 저장
> [FIX] 라이브룸 입장 퇴장시 방장이 입장할때 시간 증가 x/퇴장시 수정

- src/main/java/Growup/spring/growRoom/service/GrowRoomServiceImpl.java
- src/main/java/Growup/spring/participate/controller/ParticipateController.java
- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/dto/ParticipateDtoRes.java
- src/main/java/Growup/spring/participate/model/Enum/ParticipateStatus.java
- src/main/java/Growup/spring/participate/model/Participate.java
- src/main/java/Growup/spring/participate/repository/ParticipateRepository.java
- src/main/java/Growup/spring/participate/repository/ParticipateTimeRepository.java
- src/main/java/Growup/spring/participate/service/ParticipateService.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FEAT] 라이브룸 api 최종구현

- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FIX] 라이브룸 타이머클릭시 api 수정

- src/main/java/Growup/spring/participate/controller/ParticipateController.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FIX] post->patch로 수정

- src/main/java/Growup/spring/participate/converter/ParticipateConverter.java
- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FIX] participate 수정

- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
- src/main/java/Growup/spring/security/JwtProvider.java
[FIX] participate enter 수정 && jwt 시간 수정
> [FIX] participate enter 수정 && jwt 시간 수정

- src/main/java/Growup/spring/participate/service/ParticipateServiceImpl.java
> [FIX] participate enter 수정
